DO
$$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'prod_app') THEN
        CREATE ROLE prod_app LOGIN PASSWORD 'prod_app_pass' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
    END IF;
END
$$;

GRANT CONNECT ON DATABASE production_mvp TO prod_app;
GRANT USAGE ON SCHEMA public TO prod_app;
GRANT CREATE ON SCHEMA public TO prod_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO prod_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO prod_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO prod_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO prod_app;
